package com.pharmacy.pattern;

import com.pharmacy.entity.Drug;
import com.pharmacy.entity.Purchase;
import com.pharmacy.entity.Sale;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Implements the <b>Factory Pattern</b> for creating transactional objects.
 *
 * <p>
 * <b>Problem solved:</b> Sale and Purchase objects require consistent
 * initialization
 * logic — specifically, they must always have the current date injected at
 * creation time.
 * Scattering {@code LocalDate.now()} across caller code leads to duplication
 * and
 * potential inconsistency.
 * </p>
 *
 * <p>
 * <b>Solution:</b> This factory centralizes the creation logic. Callers simply
 * describe WHAT they want (a sale with a total, a purchase of a drug) and the
 * factory
 * handles HOW it is constructed.
 * </p>
 *
 * <p>
 * <b>Usage example:</b>
 * 
 * <pre>
 * Sale sale = TransactionFactory.createSale(new BigDecimal("49.99"));
 * Purchase purchase = TransactionFactory.createPurchase(drug, 50);
 * </pre>
 * </p>
 *
 * <p>
 * Note: This is a pure static factory. It does NOT depend on Spring beans
 * so it remains usable in non-Spring contexts (e.g. unit tests, Swing client).
 * </p>
 *
 * @see Sale
 * @see Purchase
 */
public class TransactionFactory {

    /** Prevent instantiation — all methods are static. */
    private TransactionFactory() {
        throw new UnsupportedOperationException("TransactionFactory is a static utility class.");
    }

    /**
     * Creates a new {@link Sale} with the current date and the given total amount.
     * The sale ID will be auto-generated by JPA upon persistence.
     *
     * @param totalAmount the total monetary value of the sale
     * @return a new Sale instance ready to be persisted
     */
    public static Sale createSale(BigDecimal totalAmount) {
        Sale sale = new Sale();
        sale.setTotalAmount(totalAmount);
        sale.setSaleDate(LocalDate.now()); // Factory injects current date automatically
        return sale;
    }

    /**
     * Creates a new {@link Purchase} for the given drug and quantity,
     * with the current date automatically injected.
     *
     * @param drug          the drug being purchased / restocked
     * @param quantityAdded the number of units added to stock
     * @return a new Purchase instance ready to be persisted
     */
    public static Purchase createPurchase(Drug drug, int quantityAdded) {
        Purchase purchase = new Purchase();
        purchase.setDrug(drug);
        purchase.setQuantityAdded(quantityAdded);
        purchase.setPurchaseDate(LocalDate.now()); // Factory injects current date automatically
        return purchase;
    }
}
